export { default as add_round } from './add_round.png'
export { default as backArrow } from './backArrow.png'
export { default as camera_create } from './camera-create.png'
export { default as nextArrow } from './nextArrow.png'
export { default as x } from './x.png'
export { default as downloadIcon } from './download.png'
